apiVersion: apps/v1
kind: Deployment
metadata:
  name: search-information-service-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app-2
  template:
    metadata:
      labels:
        app: my-app-2
    spec:
      containers:
        - name: my-container-2
          image: search-information-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8084
---
apiVersion: v1
kind: Service
metadata:
  name: search-information-service-service
spec:
  selector:
    app: my-app-2
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8084
  type: NodePort